apiVersion: apps/v1

kind: Deployment
metadata:

name: kubepro-deployment

spec:
replicas:3
selector:
   matchLables:
     app:kubepro
template:
  metadata:
    labels:
       app:kubepro
spec:
  containers:
    -name:kubepro
    image:vennela915/web1003
    ports:
     -containerPort:80


